---


- name: Configure nginx server in ubuntu
  copy: src=default_ubuntu.conf dest=/etc/nginx/sites-available/default
  when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian")
  notify:
    - Restart the nginx server in ubuntu


- name: Configure nginx server in centos
  copy: src=default_ucentos.conf dest=/etc/nginx/conf.d/default.conf
  when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat")
  notify:
    - Restart the nginx server in centos
