- name: Demonstrates list in Ansible
  hosts: ubuntu
  vars:
    - packages:
        - vim  
        - tree
  tasks:
    - name: Install list of software packages
      apt: name="{{item}}" state=present update_cache=yes
      with_items: "{{packages}}"
